{% set name = "treesapp" %}
{% set version = "0.6.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/hallamlab/TreeSAPP.git

build:
  number: 0
  skip: True  # [not linux64]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv; make all; make install"
#  script: "{{ PYTHON }} setup.py install -vv "  # There was a problem with attempting to install dependencies. Use pip

requirements:
  host:
    - pip
    - python >=3.5

  build:
    - python >=3.5
    - pip
    - setuptools >=45.0.0

  run:
    - python >=3.5
    - numpy >=1.18.1
    - scipy >=1.4.1
    - biopython >=1.68
    - pygtrie >=2.3.2
    - ete3 >=3.1.1
    - six >=1.14.0
    - joblib >=0.14.1
    - matplotlib >=3.1.2
    - seaborn >=0.9.0
    - hmmer >=3.1
    - prodigal >=2.6.2
    - fasttree >=2.1.9
    - bwa >=0.7.3
    - raxml ==8.2.12
    - mafft >=7.407

about:
  home: https://test.pypi.org/project/treesapp/
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  summary: "TreeSAPP is a functional and taxonomic annotation tool for microbial genomes and proteins"